export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERRORS = 'REGISTER_ERRORS';

export const QUESTIONNAIRE_CREATION_LOADING = 'QUESTIONNAIRE_CREATION_LOADING';
export const QUESTIONNAIRE_CREATION_SUCCESS = 'QUESTIONNAIRE_CREATION_SUCCESS';
export const QUESTIONNAIRE_CREATION_ERRORS = 'QUESTIONNAIRE_CREATION_ERRORS';

// export const AUTH_LOADING = 'AUTH_LOADING';
// export const AUTH_LOADING = 'AUTH_LOADING';
// export const AUTH_LOADING = 'AUTH_LOADING';
// export const AUTH_LOADING = 'AUTH_LOADING';
// export const AUTH_LOADING = 'AUTH_LOADING';
// export const AUTH_LOADING = 'AUTH_LOADING';