export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const GET_PROJECT_TASK_BY_ID = "GET_PROJECT_TASK_BY_ID";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";



// related to Questionnaire
export const GET_ALL_QUESTIONNAIRES = "GET_ALL_QUESTIONNAIRES";
export const GET_QUESTIONNAIRE_BY_ID = "GET_QUESTIONNAIRE_BY_ID";
export const GET_QUESTIONNAIRE_BY_CODE = "GET_QUESTIONNAIRE_BY_CODE";

// related to some modale

export const OPEN_EDIT_QUESTIONAIRE_MODAL = "OPEN_EDIT_QUESTIONAIRE_MODAL";


